version: '3.8'

services:
  nginx:
    build:
      context: .  # Project root context
      dockerfile: nginx/Dockerfile  # Specific Dockerfile for nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - .:/var/www
    networks:
      - varcreative-network
      - seeker

  php:
    build:
      context: .  # Project root context
      dockerfile: php/Dockerfile  # Specific Dockerfile for PHP
    container_name: php
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/var/www  # Mount application code
    networks:
      - varcreative-network
      - seeker

  #mariadb:
  #  image: mariadb:latest
  #  container_name: mariadb
  #  environment:
  #    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  #    MARIADB_DATABASE: ${DB_DATABASE}
  #    MARIADB_USER: ${DB_USERNAME}
  #    MARIADB_PASSWORD: ${DB_PASSWORD}
  #  ports:
  #    - "${DB_PORT}:3306"
  #  volumes:
  #    - db_data:/var/lib/mysql
  #  networks:
  #    - seeker

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  container_name: phpmyadmin
  #  ports:
  #    - "8080:80"  # You can change the port if necessary
  #  environment:
  #    PMA_HOST: mariadb
  #    PMA_PORT: 3306
  #    PMA_USER: ${DB_USERNAME}
  #    PMA_PASSWORD: ${DB_PASSWORD}
  #  networks:
  #    - seeker
  #  depends_on:
  #    - mariadb

volumes:
  db_data:

networks:
  varcreative-network:
    external: true
  seeker:
    driver: bridge